name: datasim
channels:
  - conda-forge
dependencies:
  - python==3.12
  - box2d-py
  - pygame
  - gymnasium[box2d]
  - pip
  - pip:
      - pandas
      - gymnasium
      - jupyterlab
      - matplotlib
      - numpy
      - swig
      - scipy
      - scikit-learn
      - stable-baselines3
      - sbx-rl
      - flax==0.11.2
      - jraph
      - pyoperon
      - tqdm
      - skorch
